import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const modulePath=process.env.FREEMAP_PLAYWRIGHT_PATH;
const {chromium}=await import(modulePath ? pathToFileURL(modulePath).href : 'playwright');
const browser=await chromium.launch({headless:true,...(process.platform==='win32' ? {executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'} : {})});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[], checks=[];
page.on('pageerror',e=>errors.push(e.message));
const ok=(name)=>{checks.push(name);console.log('PASS '+name);};
const expect=async(fn,message)=>{for(let i=0;i<50;i++){if(await fn())return;await page.waitForTimeout(100);}throw new Error(message);};
const go=async()=>{await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.find-marker');};
const setRadius=async value=>page.locator('#radius').evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);
await mkdir('screenshots',{recursive:true});
try {
  await go();
  await page.waitForTimeout(3000);
  assert.equal(await page.locator('.find-marker').count(),51);
  assert.equal(await page.locator('#visible-count').innerText(),'51');
  assert.ok(await page.locator('.leaflet-tile-loaded').count()>0);
  assert.equal(await page.locator('#map-error').isVisible(),false);
  await page.screenshot({path:'screenshots/desktop.png'});
  ok('Desktop: live map tiles, 51 radius-filtered markers and correct visible count');
  // Subsequent interaction tests do not request tiles for additional views.
  await context.route('https://tile.openstreetmap.org/**',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')}));
  await page.locator('[data-item-id="furniture-0"]').click();
  assert.equal(await page.locator('#detail-title').innerText(),'Oak lounge chair');
  assert.equal(await page.locator('#detail .source-disabled').isDisabled(),true);
  assert.ok(await page.locator('#detail').innerText().then(t=>t.includes('from City Hall')));
  await page.screenshot({path:'screenshots/detail.png'});
  ok('Detail: correct item, reference-centre distance, disabled demo source');
  await page.locator('#save-item').click();
  assert.equal(await page.locator('#stash-count').innerText(),'1');
  assert.equal(await page.locator('#save-item').getAttribute('aria-pressed'),'true');
  await go();
  assert.equal(await page.locator('#stash-count').innerText(),'1');
  await page.locator('#stash-toggle').click();
  assert.equal(await page.locator('.stash-row').count(),1);
  await page.screenshot({path:'screenshots/stash.png'});
  await page.locator('[data-open-saved="furniture-0"]').click();
  assert.equal(await page.locator('#detail-title').innerText(),'Oak lounge chair');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#detail').isVisible(),false);
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.itemId),'furniture-0');
  ok('Stash persists after reload, opens item, and Escape restores marker focus');
  await page.locator('#recenter').click();
  await page.locator('[data-category="electronics"].category').click();
  assert.ok(await page.locator('.find-marker').count()>0);
  assert.equal(await page.locator('.find-marker:not([data-category="electronics"])').count(),0);
  await page.locator('[data-item-id="electronics-0"]').click();
  await page.locator('[data-category="furniture"].category').click();
  assert.equal(await page.locator('#detail').isVisible(),false);
  ok('Category filters real markers and closes a now-excluded detail');
  await setRadius(1);
  assert.equal(await page.locator('.find-marker').count(),0);
  assert.equal(await page.locator('#empty-map').isVisible(),true);
  await page.locator('#reset-filters').click();
  await expect(async()=>await page.locator('#visible-count').innerText()==='51','Reset did not restore view');
  await setRadius(30);
  assert.equal(await page.locator('.find-marker').count(),60);
  await setRadius(10);
  ok('Radius changes the result set (0 at 1 km, 60 at 30 km); empty reset works');
  const initialPosition=await page.locator('[data-item-id="furniture-0"]').boundingBox();
  await page.locator('#zoom-in').click();
  await page.waitForTimeout(350);
  const zoomPosition=await page.locator('[data-item-id="furniture-0"]').boundingBox();
  assert.ok(Math.abs(initialPosition.x-zoomPosition.x)>5);
  await page.locator('#recenter').click();
  await page.mouse.move(1160,380);await page.mouse.down();await page.mouse.move(570,380,{steps:12});await page.mouse.up();
  await expect(async()=>Number(await page.locator('#visible-count').innerText())<51,'Pan did not update count');
  await page.locator('#recenter').click();
  ok('Zoom transforms geographic markers; panning recalculates visible results');
  await page.locator('#stash-toggle').click();
  await page.locator('[data-remove-saved="furniture-0"]').click();
  assert.equal(await page.locator('#stash-count').innerText(),'0');
  assert.equal(await page.locator('.stash-empty').isVisible(),true);
  await page.locator('#explore-from-stash').click();
  await page.locator('#demo-info').click();
  assert.equal(await page.locator('#about-dialog').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#about-dialog').isVisible(),false);
  ok('Remove favourite, empty stash and accessible demo dialog');
  await page.setViewportSize({width:390,height:844});
  await go();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'screenshots/mobile.png'});
  // Keyboard activation also works when a marker is visually behind an overlay.
  await page.locator('[data-item-id="furniture-0"]').focus();
  await page.keyboard.press('Enter');
  await expect(()=>page.locator('#detail').isVisible(),'Mobile item did not open');
  const card=await page.locator('#detail').boundingBox();
  assert.ok(card.x>=0 && card.x+card.width<=390 && card.y>=150 && card.y+card.height<=844);
  await page.screenshot({path:'screenshots/mobile-detail.png'});
  await page.locator('#save-item').click();
  await page.locator('#close-detail').click();
  await page.locator('#stash-toggle').click();
  assert.equal(await page.locator('.stash-row').count(),1);
  const stash=await page.locator('#stash-panel').boundingBox();
  assert.ok(stash.x>=0 && stash.x+stash.width<=390 && stash.y+stash.height<=844);
  ok('390 px mobile: no overflow, keyboard item activation, usable details and stash');
  await page.setViewportSize({width:1280,height:800});
  await go();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  ok('1280 px desktop has no horizontal overflow');
  await page.evaluate(()=>localStorage.setItem('freemap.stash.v1','{broken'));
  await go();
  assert.equal(await page.locator('#stash-count').innerText(),'0');
  ok('Corrupt saved data recovers safely');
  await context.route('**/assets/chair.jpg',route=>route.abort());
  await page.locator('[data-item-id="furniture-0"]').click();
  await expect(()=>page.locator('#detail .placeholder-art').isVisible(),'Photo fallback absent');
  ok('Missing photo displays a labelled category fallback');
  await context.unroute('https://tile.openstreetmap.org/**');
  await context.route('https://tile.openstreetmap.org/**',route=>route.abort());
  await go();
  await expect(()=>page.locator('#map-error').isVisible(),'Missing map failure message');
  assert.equal(await page.locator('.find-marker').count(),51);
  await context.unroute('https://tile.openstreetmap.org/**');
  await context.route('https://tile.openstreetmap.org/**',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')}));
  await page.locator('#retry-map').click();
  await expect(async()=>!(await page.locator('#map-error').isVisible()),'Retry did not clear error');
  ok('Map failure preserves markers and offers a working retry');
  assert.deepEqual(errors,[]);ok('No uncaught browser errors');
  await writeFile('screenshots/test-report.json',JSON.stringify({passed:checks.length,checks,errors},null,2));
} catch(error) {
  await page.screenshot({path:'screenshots/test-failure.png'});
  throw error;
} finally { await browser.close(); }
